name: C/C++ CI

on:
  push:
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run_tests
      run: sh run_tests.sh
